export interface City {
  name: string
  value: string
}

export interface State {
  name: string
  value: string
  cities: City[]
}

export const indianStatesAndCities: State[] = [
  {
    name: "Andhra Pradesh",
    value: "andhra-pradesh",
    cities: [
      { name: "Visakhapatnam", value: "visakhapatnam" },
      { name: "Vijayawada", value: "vijayawada" },
      { name: "Guntur", value: "guntur" },
      { name: "Nellore", value: "nellore" },
      { name: "Kurnool", value: "kurnool" },
      { name: "Rajahmundry", value: "rajahmundry" },
      { name: "Tirupati", value: "tirupati" },
      { name: "Kadapa", value: "kadapa" },
    ],
  },
  {
    name: "Arunachal Pradesh",
    value: "arunachal-pradesh",
    cities: [
      { name: "Itanagar", value: "itanagar" },
      { name: "Naharlagun", value: "naharlagun" },
      { name: "Pasighat", value: "pasighat" },
      { name: "Tezpur", value: "tezpur" },
      { name: "Bomdila", value: "bomdila" },
      { name: "Ziro", value: "ziro" },
      { name: "Along", value: "along" },
      { name: "Tezu", value: "tezu" },
    ],
  },
  {
    name: "Assam",
    value: "assam",
    cities: [
      { name: "Guwahati", value: "guwahati" },
      { name: "Dibrugarh", value: "dibrugarh" },
      { name: "Silchar", value: "silchar" },
      { name: "Jorhat", value: "jorhat" },
      { name: "Nagaon", value: "nagaon" },
      { name: "Tinsukia", value: "tinsukia" },
      { name: "Tezpur", value: "tezpur" },
      { name: "Bongaigaon", value: "bongaigaon" },
    ],
  },
  {
    name: "Bihar",
    value: "bihar",
    cities: [
      { name: "Patna", value: "patna" },
      { name: "Gaya", value: "gaya" },
      { name: "Bhagalpur", value: "bhagalpur" },
      { name: "Muzaffarpur", value: "muzaffarpur" },
      { name: "Darbhanga", value: "darbhanga" },
      { name: "Bihar Sharif", value: "bihar-sharif" },
      { name: "Arrah", value: "arrah" },
      { name: "Begusarai", value: "begusarai" },
    ],
  },
  {
    name: "Chhattisgarh",
    value: "chhattisgarh",
    cities: [
      { name: "Raipur", value: "raipur" },
      { name: "Bhilai", value: "bhilai" },
      { name: "Korba", value: "korba" },
      { name: "Bilaspur", value: "bilaspur" },
      { name: "Durg", value: "durg" },
      { name: "Rajnandgaon", value: "rajnandgaon" },
      { name: "Jagdalpur", value: "jagdalpur" },
      { name: "Raigarh", value: "raigarh" },
    ],
  },
  {
    name: "Goa",
    value: "goa",
    cities: [
      { name: "Panaji", value: "panaji" },
      { name: "Margao", value: "margao" },
      { name: "Vasco da Gama", value: "vasco-da-gama" },
      { name: "Mapusa", value: "mapusa" },
      { name: "Ponda", value: "ponda" },
      { name: "Bicholim", value: "bicholim" },
      { name: "Curchorem", value: "curchorem" },
      { name: "Sanquelim", value: "sanquelim" },
    ],
  },
  {
    name: "Gujarat",
    value: "gujarat",
    cities: [
      { name: "Ahmedabad", value: "ahmedabad" },
      { name: "Surat", value: "surat" },
      { name: "Vadodara", value: "vadodara" },
      { name: "Rajkot", value: "rajkot" },
      { name: "Bhavnagar", value: "bhavnagar" },
      { name: "Jamnagar", value: "jamnagar" },
      { name: "Gandhinagar", value: "gandhinagar" },
      { name: "Anand", value: "anand" },
    ],
  },
  {
    name: "Haryana",
    value: "haryana",
    cities: [
      { name: "Gurgaon", value: "gurgaon" },
      { name: "Faridabad", value: "faridabad" },
      { name: "Panipat", value: "panipat" },
      { name: "Ambala", value: "ambala" },
      { name: "Yamunanagar", value: "yamunanagar" },
      { name: "Rohtak", value: "rohtak" },
      { name: "Hisar", value: "hisar" },
      { name: "Karnal", value: "karnal" },
    ],
  },
  {
    name: "Himachal Pradesh",
    value: "himachal-pradesh",
    cities: [
      { name: "Shimla", value: "shimla" },
      { name: "Dharamshala", value: "dharamshala" },
      { name: "Solan", value: "solan" },
      { name: "Mandi", value: "mandi" },
      { name: "Palampur", value: "palampur" },
      { name: "Baddi", value: "baddi" },
      { name: "Nahan", value: "nahan" },
      { name: "Una", value: "una" },
    ],
  },
  {
    name: "Jharkhand",
    value: "jharkhand",
    cities: [
      { name: "Ranchi", value: "ranchi" },
      { name: "Jamshedpur", value: "jamshedpur" },
      { name: "Dhanbad", value: "dhanbad" },
      { name: "Bokaro", value: "bokaro" },
      { name: "Deoghar", value: "deoghar" },
      { name: "Phusro", value: "phusro" },
      { name: "Hazaribagh", value: "hazaribagh" },
      { name: "Giridih", value: "giridih" },
    ],
  },
  {
    name: "Karnataka",
    value: "karnataka",
    cities: [
      { name: "Bangalore", value: "bangalore" },
      { name: "Mysore", value: "mysore" },
      { name: "Hubli", value: "hubli" },
      { name: "Mangalore", value: "mangalore" },
      { name: "Belgaum", value: "belgaum" },
      { name: "Gulbarga", value: "gulbarga" },
      { name: "Davangere", value: "davangere" },
      { name: "Bellary", value: "bellary" },
    ],
  },
  {
    name: "Kerala",
    value: "kerala",
    cities: [
      { name: "Thiruvananthapuram", value: "thiruvananthapuram" },
      { name: "Kochi", value: "kochi" },
      { name: "Kozhikode", value: "kozhikode" },
      { name: "Thrissur", value: "thrissur" },
      { name: "Kollam", value: "kollam" },
      { name: "Palakkad", value: "palakkad" },
      { name: "Alappuzha", value: "alappuzha" },
      { name: "Malappuram", value: "malappuram" },
    ],
  },
  {
    name: "Madhya Pradesh",
    value: "madhya-pradesh",
    cities: [
      { name: "Bhopal", value: "bhopal" },
      { name: "Indore", value: "indore" },
      { name: "Gwalior", value: "gwalior" },
      { name: "Jabalpur", value: "jabalpur" },
      { name: "Ujjain", value: "ujjain" },
      { name: "Sagar", value: "sagar" },
      { name: "Dewas", value: "dewas" },
      { name: "Satna", value: "satna" },
    ],
  },
  {
    name: "Maharashtra",
    value: "maharashtra",
    cities: [
      { name: "Mumbai", value: "mumbai" },
      { name: "Pune", value: "pune" },
      { name: "Nagpur", value: "nagpur" },
      { name: "Nashik", value: "nashik" },
      { name: "Aurangabad", value: "aurangabad" },
      { name: "Solapur", value: "solapur" },
      { name: "Thane", value: "thane" },
      { name: "Kolhapur", value: "kolhapur" },
    ],
  },
  {
    name: "Manipur",
    value: "manipur",
    cities: [
      { name: "Imphal", value: "imphal" },
      { name: "Thoubal", value: "thoubal" },
      { name: "Bishnupur", value: "bishnupur" },
      { name: "Churachandpur", value: "churachandpur" },
      { name: "Ukhrul", value: "ukhrul" },
      { name: "Senapati", value: "senapati" },
      { name: "Tamenglong", value: "tamenglong" },
      { name: "Chandel", value: "chandel" },
    ],
  },
  {
    name: "Meghalaya",
    value: "meghalaya",
    cities: [
      { name: "Shillong", value: "shillong" },
      { name: "Tura", value: "tura" },
      { name: "Jowai", value: "jowai" },
      { name: "Nongpoh", value: "nongpoh" },
      { name: "Baghmara", value: "baghmara" },
      { name: "Williamnagar", value: "williamnagar" },
      { name: "Resubelpara", value: "resubelpara" },
      { name: "Mawkyrwat", value: "mawkyrwat" },
    ],
  },
  {
    name: "Mizoram",
    value: "mizoram",
    cities: [
      { name: "Aizawl", value: "aizawl" },
      { name: "Lunglei", value: "lunglei" },
      { name: "Saiha", value: "saiha" },
      { name: "Champhai", value: "champhai" },
      { name: "Kolasib", value: "kolasib" },
      { name: "Serchhip", value: "serchhip" },
      { name: "Mamit", value: "mamit" },
      { name: "Lawngtlai", value: "lawngtlai" },
    ],
  },
  {
    name: "Nagaland",
    value: "nagaland",
    cities: [
      { name: "Kohima", value: "kohima" },
      { name: "Dimapur", value: "dimapur" },
      { name: "Mokokchung", value: "mokokchung" },
      { name: "Tuensang", value: "tuensang" },
      { name: "Wokha", value: "wokha" },
      { name: "Zunheboto", value: "zunheboto" },
      { name: "Phek", value: "phek" },
      { name: "Kiphire", value: "kiphire" },
    ],
  },
  {
    name: "Odisha",
    value: "odisha",
    cities: [
      { name: "Bhubaneswar", value: "bhubaneswar" },
      { name: "Cuttack", value: "cuttack" },
      { name: "Rourkela", value: "rourkela" },
      { name: "Berhampur", value: "berhampur" },
      { name: "Sambalpur", value: "sambalpur" },
      { name: "Puri", value: "puri" },
      { name: "Balasore", value: "balasore" },
      { name: "Bhadrak", value: "bhadrak" },
    ],
  },
  {
    name: "Punjab",
    value: "punjab",
    cities: [
      { name: "Chandigarh", value: "chandigarh" },
      { name: "Ludhiana", value: "ludhiana" },
      { name: "Amritsar", value: "amritsar" },
      { name: "Jalandhar", value: "jalandhar" },
      { name: "Patiala", value: "patiala" },
      { name: "Bathinda", value: "bathinda" },
      { name: "Mohali", value: "mohali" },
      { name: "Firozpur", value: "firozpur" },
    ],
  },
  {
    name: "Rajasthan",
    value: "rajasthan",
    cities: [
      { name: "Jaipur", value: "jaipur" },
      { name: "Jodhpur", value: "jodhpur" },
      { name: "Udaipur", value: "udaipur" },
      { name: "Kota", value: "kota" },
      { name: "Bikaner", value: "bikaner" },
      { name: "Ajmer", value: "ajmer" },
      { name: "Bhilwara", value: "bhilwara" },
      { name: "Alwar", value: "alwar" },
    ],
  },
  {
    name: "Sikkim",
    value: "sikkim",
    cities: [
      { name: "Gangtok", value: "gangtok" },
      { name: "Namchi", value: "namchi" },
      { name: "Geyzing", value: "geyzing" },
      { name: "Mangan", value: "mangan" },
      { name: "Jorethang", value: "jorethang" },
      { name: "Rangpo", value: "rangpo" },
      { name: "Singtam", value: "singtam" },
      { name: "Pakyong", value: "pakyong" },
    ],
  },
  {
    name: "Tamil Nadu",
    value: "tamil-nadu",
    cities: [
      { name: "Chennai", value: "chennai" },
      { name: "Coimbatore", value: "coimbatore" },
      { name: "Madurai", value: "madurai" },
      { name: "Tiruchirappalli", value: "tiruchirappalli" },
      { name: "Salem", value: "salem" },
      { name: "Tirunelveli", value: "tirunelveli" },
      { name: "Erode", value: "erode" },
      { name: "Vellore", value: "vellore" },
    ],
  },
  {
    name: "Telangana",
    value: "telangana",
    cities: [
      { name: "Hyderabad", value: "hyderabad" },
      { name: "Warangal", value: "warangal" },
      { name: "Nizamabad", value: "nizamabad" },
      { name: "Khammam", value: "khammam" },
      { name: "Karimnagar", value: "karimnagar" },
      { name: "Ramagundam", value: "ramagundam" },
      { name: "Mahbubnagar", value: "mahbubnagar" },
      { name: "Nalgonda", value: "nalgonda" },
    ],
  },
  {
    name: "Tripura",
    value: "tripura",
    cities: [
      { name: "Agartala", value: "agartala" },
      { name: "Dharmanagar", value: "dharmanagar" },
      { name: "Udaipur", value: "udaipur-tripura" },
      { name: "Kailasahar", value: "kailasahar" },
      { name: "Belonia", value: "belonia" },
      { name: "Khowai", value: "khowai" },
      { name: "Ambassa", value: "ambassa" },
      { name: "Ranir Bazar", value: "ranir-bazar" },
    ],
  },
  {
    name: "Uttar Pradesh",
    value: "uttar-pradesh",
    cities: [
      { name: "Lucknow", value: "lucknow" },
      { name: "Kanpur", value: "kanpur" },
      { name: "Ghaziabad", value: "ghaziabad" },
      { name: "Agra", value: "agra" },
      { name: "Varanasi", value: "varanasi" },
      { name: "Meerut", value: "meerut" },
      { name: "Allahabad", value: "allahabad" },
      { name: "Bareilly", value: "bareilly" },
    ],
  },
  {
    name: "Uttarakhand",
    value: "uttarakhand",
    cities: [
      { name: "Dehradun", value: "dehradun" },
      { name: "Haridwar", value: "haridwar" },
      { name: "Roorkee", value: "roorkee" },
      { name: "Haldwani", value: "haldwani" },
      { name: "Rudrapur", value: "rudrapur" },
      { name: "Kashipur", value: "kashipur" },
      { name: "Rishikesh", value: "rishikesh" },
      { name: "Kotdwar", value: "kotdwar" },
    ],
  },
  {
    name: "West Bengal",
    value: "west-bengal",
    cities: [
      { name: "Kolkata", value: "kolkata" },
      { name: "Howrah", value: "howrah" },
      { name: "Durgapur", value: "durgapur" },
      { name: "Asansol", value: "asansol" },
      { name: "Siliguri", value: "siliguri" },
      { name: "Malda", value: "malda" },
      { name: "Bardhaman", value: "bardhaman" },
      { name: "Kharagpur", value: "kharagpur" },
    ],
  },
  // Union Territories
  {
    name: "Andaman & Nicobar Islands",
    value: "andaman-nicobar",
    cities: [
      { name: "Port Blair", value: "port-blair" },
      { name: "Car Nicobar", value: "car-nicobar" },
      { name: "Mayabunder", value: "mayabunder" },
      { name: "Rangat", value: "rangat" },
      { name: "Diglipur", value: "diglipur" },
      { name: "Campbell Bay", value: "campbell-bay" },
      { name: "Nancowry", value: "nancowry" },
      { name: "Little Andaman", value: "little-andaman" },
    ],
  },
  {
    name: "Chandigarh",
    value: "chandigarh",
    cities: [
      { name: "Chandigarh", value: "chandigarh-city" },
      { name: "Sector 17", value: "sector-17" },
      { name: "Sector 22", value: "sector-22" },
      { name: "Sector 35", value: "sector-35" },
      { name: "Manimajra", value: "manimajra" },
      { name: "Panchkula", value: "panchkula" },
      { name: "Mohali", value: "mohali-chandigarh" },
      { name: "Zirakpur", value: "zirakpur" },
    ],
  },
  {
    name: "Dadra & Nagar Haveli and Daman & Diu",
    value: "dadra-nagar-haveli-daman-diu",
    cities: [
      { name: "Daman", value: "daman" },
      { name: "Diu", value: "diu" },
      { name: "Silvassa", value: "silvassa" },
      { name: "Vapi", value: "vapi" },
      { name: "Naroli", value: "naroli" },
      { name: "Khanvel", value: "khanvel" },
      { name: "Samarvarni", value: "samarvarni" },
      { name: "Dunetha", value: "dunetha" },
    ],
  },
  {
    name: "Delhi",
    value: "delhi",
    cities: [
      { name: "New Delhi", value: "new-delhi" },
      { name: "Gurgaon", value: "gurgaon" },
      { name: "Noida", value: "noida" },
      { name: "Faridabad", value: "faridabad" },
      { name: "Ghaziabad", value: "ghaziabad" },
      { name: "Greater Noida", value: "greater-noida" },
      { name: "Dwarka", value: "dwarka" },
      { name: "Rohini", value: "rohini" },
    ],
  },
  {
    name: "Jammu & Kashmir",
    value: "jammu-kashmir",
    cities: [
      { name: "Srinagar", value: "srinagar" },
      { name: "Jammu", value: "jammu" },
      { name: "Anantnag", value: "anantnag" },
      { name: "Baramulla", value: "baramulla" },
      { name: "Sopore", value: "sopore" },
      { name: "Kathua", value: "kathua" },
      { name: "Udhampur", value: "udhampur" },
      { name: "Punch", value: "punch" },
    ],
  },
  {
    name: "Ladakh",
    value: "ladakh",
    cities: [
      { name: "Leh", value: "leh" },
      { name: "Kargil", value: "kargil" },
      { name: "Nubra", value: "nubra" },
      { name: "Zanskar", value: "zanskar" },
      { name: "Drass", value: "drass" },
      { name: "Khaltse", value: "khaltse" },
      { name: "Nyoma", value: "nyoma" },
      { name: "Nobra", value: "nobra" },
    ],
  },
  {
    name: "Lakshadweep",
    value: "lakshadweep",
    cities: [
      { name: "Kavaratti", value: "kavaratti" },
      { name: "Agatti", value: "agatti" },
      { name: "Minicoy", value: "minicoy" },
      { name: "Amini", value: "amini" },
      { name: "Andrott", value: "andrott" },
      { name: "Kalpeni", value: "kalpeni" },
      { name: "Kadmat", value: "kadmat" },
      { name: "Bangaram", value: "bangaram" },
    ],
  },
  {
    name: "Puducherry",
    value: "puducherry",
    cities: [
      { name: "Puducherry", value: "puducherry-city" },
      { name: "Karaikal", value: "karaikal" },
      { name: "Yanam", value: "yanam" },
      { name: "Mahe", value: "mahe" },
      { name: "Villianur", value: "villianur" },
      { name: "Ariyankuppam", value: "ariyankuppam" },
      { name: "Mannadipet", value: "mannadipet" },
      { name: "Bahour", value: "bahour" },
    ],
  },
]
